export enum ClaimType {
    IdentityProvider = "!",
    UserIdentifier = '"',
    UserLogonName = "#",
    DistributionListClaimType = "$",
    FarmId = "%",
    ProcessIdentitySid = "&",
    ProcessIdentityLogonName = "'", // GroupSid?
    IsAuthenticated = "(",
    PrimarySid = ")",
    PrimaryGroupSid = "*",
    GroupSid = "+",
    Role = "-",
    Anonymous = ".",
    Authentication = "/",
    AuthorizationDecision = "0",
    Country = "1",
    DateOfBirth = "2",
    DenyOnlySid = "3",
    Dns = "4",
    Email = "5",
    Gender = "6",
    GivenName = "7",
    Hash = "8",
    HomePhone = "9",
    Locality = "<",
    MobilePhone = "=",
    Name = ">",
    NameIdentifier = "?",
    OtherPhone = "@",
    PostalCode = "[",
    PPID = "\\",
    Rsa = "]",
    Sid = "^",
    Spn = "_",
    StateOrProvince = "`",
    StreetAddress = "a",
    Surname = "b",
    System = "c",
    Thumbprint = "d",
    Upn = "e",
    Uri = "f",
    Webpage = "g",
    ProviderUserKey = "h",
    NameId = "i",
    UserPrincipalName = "j",
    NameIdIssuer = "k",
    SMTP = "l",
    SIP = "m",
    ClaimProviderContext = "n"
}

export const ClaimTypeNames = {
    [ClaimType.IdentityProvider]: "IdentityProvider",
    [ClaimType.UserIdentifier]: "UserIdentifier",
    [ClaimType.UserLogonName]: "UserLogonName",
    [ClaimType.DistributionListClaimType]: "DistributionListClaimType",
    [ClaimType.FarmId]: "FarmId",
    [ClaimType.ProcessIdentitySid]: "ProcessIdentitySid",
    [ClaimType.ProcessIdentityLogonName]: "ProcessIdentityLogonName",
    [ClaimType.IsAuthenticated]: "IsAuthenticated",
    [ClaimType.PrimarySid]: "PrimarySid",
    [ClaimType.PrimaryGroupSid]: "PrimaryGroupSid",
    [ClaimType.GroupSid]: "GroupSid",
    [ClaimType.Role]: "Role",
    [ClaimType.Anonymous]: "Anonymous",
    [ClaimType.Authentication]: "Authentication",
    [ClaimType.AuthorizationDecision]: "AuthorizationDecision",
    [ClaimType.Country]: "Country",
    [ClaimType.DateOfBirth]: "DateOfBirth",
    [ClaimType.DenyOnlySid]: "DenyOnlySid",
    [ClaimType.Dns]: "Dns",
    [ClaimType.Email]: "Email",
    [ClaimType.Gender]: "Gender",
    [ClaimType.GivenName]: "GivenName",
    [ClaimType.Hash]: "Hash",
    [ClaimType.HomePhone]: "HomePhone",
    [ClaimType.Locality]: "Locality",
    [ClaimType.MobilePhone]: "MobilePhone",
    [ClaimType.Name]: "Name",
    [ClaimType.NameIdentifier]: "NameIdentifier",
    [ClaimType.OtherPhone]: "OtherPhone",
    [ClaimType.PostalCode]: "PostalCode",
    [ClaimType.PPID]: "PPID",
    [ClaimType.Rsa]: "Rsa",
    [ClaimType.Sid]: "Sid",
    [ClaimType.Spn]: "Spn",
    [ClaimType.StateOrProvince]: "StateOrProvince",
    [ClaimType.StreetAddress]: "StreetAddress",
    [ClaimType.Surname]: "Surname",
    [ClaimType.System]: "System",
    [ClaimType.Thumbprint]: "Thumbprint",
    [ClaimType.Upn]: "Upn",
    [ClaimType.Uri]: "Uri",
    [ClaimType.Webpage]: "Webpage",
    [ClaimType.ProviderUserKey]: "ProviderUserKey",
    [ClaimType.NameId]: "NameId",
    [ClaimType.UserPrincipalName]: "UserPrincipalName",
    [ClaimType.NameIdIssuer]: "NameIdIssuer",
    [ClaimType.SMTP]: "SMTP",
    [ClaimType.SIP]: "SIP",
    [ClaimType.ClaimProviderContext]: "ClaimProviderContext",
}
