import {ChangeTokenResponse} from "../change/index.js";
import {PathResponse} from "../filesystem/index.js";

export interface ListResponse {
    Id: string;
    ListItemEntityTypeFullName: string;
    ItemCount: number;
    Title: string;
    Description: string;
    CurrentChangeToken: ChangeTokenResponse;
    Hidden: boolean;
    IsPrivate: boolean;
    AllowContentTypes: boolean;
    BaseTemplate: number;
    BaseType: number;
    ContentTypesEnabled: boolean;
    CrawlNonDefaultViews: boolean;
    Created: string; //Date
    DefaultContentApprovalWorkflowId: string;
    DefaultItemOpenUseListSetting: boolean;
    Direction: string;
    DisableCommenting: boolean;
    DisableGridEditing: boolean;
    DocumentTemplateUrl: string;
    DraftVersionVisibility: number;
    EnableAttachments: boolean;
    EnableFolderCreation: boolean;
    EnableMinorVersion: boolean;
    EnableModeration: boolean;
    EnableRequestSignOff: boolean;
    EnableVersioning: boolean;
    EntityTypeName: string;
    ExemptFromBlockDownloadOfNonViewableFiles: boolean;
    FileSavePostProcessingEnabled: boolean;
    ForceCheckout: boolean;
    HasExternalDataSource: boolean;
    ImagePath: PathResponse;
    ImageUrl: string;
    DefaultSensitivityLabelForLibrary: string;
    SensitivityLabelToEncryptOnDownloadForLibrary: null;
    IrmEnabled: boolean;
    IrmExpire: boolean;
    IrmReject: boolean;
    IsApplicationList: boolean;
    IsCatalog: boolean;
    LastItemDeletedDate: string;
    LastItemModifiedDate: string;
    LastItemUserModifiedDate: string;
    ListExperienceOptions: number;
    MajorVersionLimit: number;
    MajorWithMinorVersionsLimit: number;
    MultipleDataList: boolean;
    NoCrawl: boolean;
    ParentWebPath: PathResponse;
    ParentWebUrl: string;
    ParserDisabled: boolean;
    ServerTemplateCanCreateFolders: boolean;
    TemplateFeatureId: string;
}